### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Ch3wi3** [MaximilianClemens/checkmk_fritzbox#1]
Hello, 

I have difficulites to integrate this agent into my checkmk installation. I thought I just have to copy all files from this repo to the appropriate locations within my checkmk directories, but somehow the parameters for username and password are not visible in wato after that. Could you provide an installation guide please?

**Comment by MaximilianClemens** [comment]
Hello,

I added a small instruction to the README.MD. Essentially, but not tested yet:
1. Grab the current release from: https://github.com/MaximilianClemens/checkmk_fritzbox/releases
2. Follow the instructions to install a mkp = https://checkmk.com/cms_omd_basics.html

Regards
Maximilian

**Comment by ambergerit** [comment]
Hello Maximilian,

I have the same issue. I installed it using the mkp command. After that you wrote „there should now be a new option "Query SmartHome Devices"“ but it is not. Only the old one, where i can set the timeout value. 

In Host and service parameters there is a new entry „Settings for Fritz!Box Smarthome Devices“ where i could set parameters for the smarthome warning/critical states. 


The (bevore plugin installation) activated fritz Hosts get now error state:

Fetching 'agent'...
Failed: [special_fritzbox] Agent exited with code 2: usage: agent_fritzbox [-h] [--debug] [--timeout TIMEOUT] [--check-upnp]
                      [--check-smarthome]
                      host [username] [password] [port] [{http,https}]
agent_fritzbox: error: port must be between 1 and 65565
(!!)

Finished. Click on the icon to download the data.

So it will use the new plugin, but i cannot configure it, to get it working, due the parameters are not show up in wato.
But if i cannot set the values in the host and service parameters how will,i get this working again. Seems that the new parameters site isn‘t been loading in „Check state of Fritz!Box Devices“ so the system loads the original check_mk site (i‘ve attatched a screenshot).
Can you provide a solution for this? 
![B6E78C71-CD0A-44A9-9C63-841625354087](https://user-images.githubusercontent.com/6476053/95666718-ba929f00-0b5c-11eb-90f1-5574fa5e4238.jpeg)
