### ISSUE TITLE
Not working in Checkmk 2.0.0p1

### ISSUE THREAD

**Issue by Domanaik** [MaximilianClemens/checkmk_fritzbox#5]
Can you update the package so it works in Checkmk  2.0.0p1 too?
I can install like in 1.6 but it's not showing in the menu to configure.

**Comment by MaximilianClemens** [comment]
Hi @Domanaik,

can you try: [v0.5.4](https://github.com/MaximilianClemens/checkmk_fritzbox/releases/tag/v0.5.4-cmk2).
I've made some changes for cmk2, and it seemd to work now:
![grafik](https://user-images.githubusercontent.com/5416563/114218515-cd4e2b00-9969-11eb-82e0-b6eadcb1faee.png)
![grafik](https://user-images.githubusercontent.com/5416563/114218621-efe04400-9969-11eb-8fda-6f0a12453999.png)

Regards
Maximilian

**Comment by Domanaik** [comment]
Hi @MaximilianClemens 

thank you for your fast response. Its working like a charm 👍 

![image](https://user-images.githubusercontent.com/63446985/114235455-8455a100-9980-11eb-89db-2283843efe4e.png)

**Comment by Domanaik** [comment]
Hm, something is not right tho. I can see it in WATO Service configuration. But on host is not showing. Discovery is telling my its 7 vanished services:
![image](https://user-images.githubusercontent.com/63446985/114236437-e531a900-9981-11eb-9ebe-3286fa66631b.png)

**Comment by Domanaik** [comment]
I found the problem. After "Remove all and find new" its working. Maybe its from the update. Thanks!
