### ISSUE TITLE
Support for FD440 Humidity Sensor

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [MaximilianClemens/checkmk_fritzbox#6]
Hello, first a big "Thank you" for your work. I love the check.
Is there a chance to integrate the humidity sensor for the AVM FritzDect 440 Switches introduced in v7.24 ?

**Comment by MaximilianClemens** [comment]
Hello @FlyinFistOfJuda,
thanks for the feedback :)

I'll try to add the sensor, can you send me the Agent output from the FritzBox where the FD440 is connected?
(Please check if the output contains sensitive Information before posting and remove them if necessary)
![image](https://user-images.githubusercontent.com/5416563/134571568-23333927-94b6-4ecd-b644-d35e4dc0979e.png)

Regards
Max

**Comment by FlyinFistOfJuda** [comment]
Thanks mate, here we go...
[check_mk-fritz.box-agent.txt](https://github.com/MaximilianClemens/checkmk_fritzbox/files/7224934/check_mk-fritz.box-agent.txt)

**Comment by MaximilianClemens** [comment]
Thanks @FlyinFistOfJuda,

can you try release [v0.5.5](https://github.com/MaximilianClemens/checkmk_fritzbox/releases/tag/v0.5.5).
Hope this works for you, the Thresholds are configurable:
![image](https://user-images.githubusercontent.com/5416563/134696982-004ec0a5-245d-4598-8560-e7f46820d98a.png)

Regards
Max

**Comment by MaximilianClemens** [comment]
I made some small Changes and created [v0.5.6](https://github.com/MaximilianClemens/checkmk_fritzbox/releases/tag/v0.5.6).
If you already tested v0.5.5 you may have to recreate the old rules.

**Comment by FlyinFistOfJuda** [comment]
Thank you very much for your effort, works like a charm! 🥳
